.PHONY: install 
.DEFAULT_GOAL := install

install:
	pip3 install -r requirements.txt
	pip3 install awscli --upgrade --user
	pip3 install importlib-metadata --upgrade --user
	pip3 install twine --upgrade --user